# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './activeGroup.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_activeGroup(object):
    def setupUi(self, activeGroup):
        activeGroup.setObjectName("activeGroup")
        activeGroup.resize(616, 488)
        self.verticalLayout = QtWidgets.QVBoxLayout(activeGroup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(activeGroup)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.groupLabel = QtWidgets.QLabel(activeGroup)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupLabel.setFont(font)
        self.groupLabel.setObjectName("groupLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.groupLabel)
        self.label_3 = QtWidgets.QLabel(activeGroup)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.libraryLabel = QtWidgets.QLabel(activeGroup)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.libraryLabel.setFont(font)
        self.libraryLabel.setObjectName("libraryLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.libraryLabel)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.editLibraryButton = QtWidgets.QPushButton(activeGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editLibraryButton.sizePolicy().hasHeightForWidth())
        self.editLibraryButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.editLibraryButton.setFont(font)
        self.editLibraryButton.setObjectName("editLibraryButton")
        self.horizontalLayout_2.addWidget(self.editLibraryButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(activeGroup)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.listWidget = QtWidgets.QListWidget(activeGroup)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.openEncounterButton = QtWidgets.QPushButton(activeGroup)
        self.openEncounterButton.setObjectName("openEncounterButton")
        self.verticalLayout_2.addWidget(self.openEncounterButton)
        self.addEncounterButton = QtWidgets.QPushButton(activeGroup)
        self.addEncounterButton.setObjectName("addEncounterButton")
        self.verticalLayout_2.addWidget(self.addEncounterButton)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(activeGroup)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.listWidget_2 = QtWidgets.QListWidget(activeGroup)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_3.addWidget(self.listWidget_2)
        self.openTableButton = QtWidgets.QPushButton(activeGroup)
        self.openTableButton.setObjectName("openTableButton")
        self.verticalLayout_3.addWidget(self.openTableButton)
        self.addTableButton = QtWidgets.QPushButton(activeGroup)
        self.addTableButton.setObjectName("addTableButton")
        self.verticalLayout_3.addWidget(self.addTableButton)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.exitButton = QtWidgets.QPushButton(activeGroup)
        self.exitButton.setObjectName("exitButton")
        self.verticalLayout.addWidget(self.exitButton)

        self.retranslateUi(activeGroup)
        QtCore.QMetaObject.connectSlotsByName(activeGroup)

    def retranslateUi(self, activeGroup):
        _translate = QtCore.QCoreApplication.translate
        activeGroup.setWindowTitle(_translate("activeGroup", "Form"))
        self.label.setText(_translate("activeGroup", "Current Group: "))
        self.groupLabel.setText(_translate("activeGroup", "TextLabel"))
        self.label_3.setText(_translate("activeGroup", "Group Library: "))
        self.libraryLabel.setText(_translate("activeGroup", "TextLabel"))
        self.editLibraryButton.setText(_translate("activeGroup", "Edit Library"))
        self.label_2.setText(_translate("activeGroup", "Encounters"))
        self.openEncounterButton.setText(_translate("activeGroup", "Open Encounter"))
        self.addEncounterButton.setText(_translate("activeGroup", "Add Encounter"))
        self.label_4.setText(_translate("activeGroup", "Random Tables"))
        self.openTableButton.setText(_translate("activeGroup", "Open Table"))
        self.addTableButton.setText(_translate("activeGroup", "Add Table"))
        self.exitButton.setText(_translate("activeGroup", "Exit"))

