# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './addEncounter.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_addEncounter(object):
    def setupUi(self, addEncounter):
        addEncounter.setObjectName("addEncounter")
        addEncounter.resize(1524, 684)
        self.verticalLayout = QtWidgets.QVBoxLayout(addEncounter)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(addEncounter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.encounterNameEdit = QtWidgets.QLineEdit(addEncounter)
        self.encounterNameEdit.setObjectName("encounterNameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.encounterNameEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.currentEncounterTable = QtWidgets.QTableWidget(addEncounter)
        self.currentEncounterTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.currentEncounterTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.currentEncounterTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.currentEncounterTable.setObjectName("currentEncounterTable")
        self.currentEncounterTable.setColumnCount(0)
        self.currentEncounterTable.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.currentEncounterTable)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.removeFilterButton = QtWidgets.QPushButton(addEncounter)
        self.removeFilterButton.setObjectName("removeFilterButton")
        self.verticalLayout_3.addWidget(self.removeFilterButton)
        self.filterList = QtWidgets.QListWidget(addEncounter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterList.sizePolicy().hasHeightForWidth())
        self.filterList.setSizePolicy(sizePolicy)
        self.filterList.setObjectName("filterList")
        self.verticalLayout_3.addWidget(self.filterList)
        self.addButton = QtWidgets.QPushButton(addEncounter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.verticalLayout_3.addWidget(self.addButton)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(addEncounter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.qtyCount = QtWidgets.QSpinBox(addEncounter)
        self.qtyCount.setMinimum(1)
        self.qtyCount.setProperty("value", 1)
        self.qtyCount.setObjectName("qtyCount")
        self.horizontalLayout_4.addWidget(self.qtyCount)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.removeButton = QtWidgets.QPushButton(addEncounter)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.removeButton.setFont(font)
        self.removeButton.setObjectName("removeButton")
        self.verticalLayout_3.addWidget(self.removeButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.filterFieldBox = QtWidgets.QComboBox(addEncounter)
        self.filterFieldBox.setObjectName("filterFieldBox")
        self.horizontalLayout_3.addWidget(self.filterFieldBox)
        self.filterEdit = QtWidgets.QLineEdit(addEncounter)
        self.filterEdit.setObjectName("filterEdit")
        self.horizontalLayout_3.addWidget(self.filterEdit)
        self.addFilterButton = QtWidgets.QPushButton(addEncounter)
        self.addFilterButton.setObjectName("addFilterButton")
        self.horizontalLayout_3.addWidget(self.addFilterButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.libraryTable = QtWidgets.QTableWidget(addEncounter)
        self.libraryTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.libraryTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.libraryTable.setObjectName("libraryTable")
        self.libraryTable.setColumnCount(0)
        self.libraryTable.setRowCount(0)
        self.verticalLayout_2.addWidget(self.libraryTable)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.acceptButton = QtWidgets.QPushButton(addEncounter)
        self.acceptButton.setObjectName("acceptButton")
        self.horizontalLayout.addWidget(self.acceptButton)
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.cancelButton = QtWidgets.QPushButton(addEncounter)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(addEncounter)
        QtCore.QMetaObject.connectSlotsByName(addEncounter)

    def retranslateUi(self, addEncounter):
        _translate = QtCore.QCoreApplication.translate
        addEncounter.setWindowTitle(_translate("addEncounter", "Add Encounter"))
        self.label.setText(_translate("addEncounter", "Encounter Name: "))
        self.removeFilterButton.setText(_translate("addEncounter", "Remove Filter"))
        self.addButton.setText(_translate("addEncounter", "<--Add--<"))
        self.label_2.setText(_translate("addEncounter", "Qty: "))
        self.removeButton.setText(_translate("addEncounter", ">--Remove-->"))
        self.addFilterButton.setText(_translate("addEncounter", "Add Filter"))
        self.libraryTable.setSortingEnabled(True)
        self.acceptButton.setText(_translate("addEncounter", "Accept"))
        self.cancelButton.setText(_translate("addEncounter", "Cancel"))

