# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './newTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_newTemplate(object):
    def setupUi(self, newTemplate):
        newTemplate.setObjectName("newTemplate")
        newTemplate.resize(634, 536)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(newTemplate)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(newTemplate)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(newTemplate)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(newTemplate)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.templateName = QtWidgets.QLineEdit(newTemplate)
        self.templateName.setObjectName("templateName")
        self.gridLayout.addWidget(self.templateName, 3, 1, 1, 1)
        self.gameSystem = QtWidgets.QLineEdit(newTemplate)
        self.gameSystem.setObjectName("gameSystem")
        self.gridLayout.addWidget(self.gameSystem, 4, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.label_3 = QtWidgets.QLabel(newTemplate)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.fieldList = QtWidgets.QListWidget(newTemplate)
        self.fieldList.setObjectName("fieldList")
        self.verticalLayout_2.addWidget(self.fieldList)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(newTemplate)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.fieldToAdd = QtWidgets.QLineEdit(newTemplate)
        self.fieldToAdd.setObjectName("fieldToAdd")
        self.horizontalLayout.addWidget(self.fieldToAdd)
        self.label_6 = QtWidgets.QLabel(newTemplate)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.textButton = QtWidgets.QRadioButton(newTemplate)
        self.textButton.setObjectName("textButton")
        self.horizontalLayout.addWidget(self.textButton)
        self.intButton = QtWidgets.QRadioButton(newTemplate)
        self.intButton.setObjectName("intButton")
        self.horizontalLayout.addWidget(self.intButton)
        self.addFieldButton = QtWidgets.QPushButton(newTemplate)
        self.addFieldButton.setObjectName("addFieldButton")
        self.horizontalLayout.addWidget(self.addFieldButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(newTemplate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.createTemplateButton = QtWidgets.QPushButton(newTemplate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createTemplateButton.sizePolicy().hasHeightForWidth())
        self.createTemplateButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.createTemplateButton.setFont(font)
        self.createTemplateButton.setObjectName("createTemplateButton")
        self.horizontalLayout_3.addWidget(self.createTemplateButton)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.returnButton = QtWidgets.QPushButton(newTemplate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.returnButton.sizePolicy().hasHeightForWidth())
        self.returnButton.setSizePolicy(sizePolicy)
        self.returnButton.setObjectName("returnButton")
        self.horizontalLayout_2.addWidget(self.returnButton)
        spacerItem4 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(newTemplate)
        QtCore.QMetaObject.connectSlotsByName(newTemplate)

    def retranslateUi(self, newTemplate):
        _translate = QtCore.QCoreApplication.translate
        newTemplate.setWindowTitle(_translate("newTemplate", "Dungeon Journal - New Template"))
        self.label.setText(_translate("newTemplate", "Create New Template"))
        self.label_5.setText(_translate("newTemplate", "Template Name: "))
        self.label_4.setText(_translate("newTemplate", "Game System: "))
        self.label_3.setText(_translate("newTemplate", "Fields to be included in template:"))
        self.label_2.setText(_translate("newTemplate", "Attribute Name:"))
        self.label_6.setText(_translate("newTemplate", "Value Type: "))
        self.textButton.setText(_translate("newTemplate", "Text"))
        self.intButton.setText(_translate("newTemplate", "Integer"))
        self.addFieldButton.setText(_translate("newTemplate", "Add to Template"))
        self.createTemplateButton.setText(_translate("newTemplate", "Create Template"))
        self.returnButton.setText(_translate("newTemplate", "Return to Main Menu"))

